<a href="https://colab.research.google.com/github/wenjunsun/personal-machine-learning-projects/blob/master/boltzmann-machine/Hopfield_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# How does memory work?

This is a very exciting field for me: How does human store memory? Is there a way to computationally mimic that mechanism? 

It is well known in the neuroscience that a specific factoid/memory is not stored in a particular neuron, but stored in the network of neurons and their interconnections. Humans can extract the right memory from partial incorrect information, something that computers can't do yet. 

In the following I will use a very simple and yet elegant idea from Hopfield (an American scientist, who came up with this idea in 1980's), to demonstrate how we can implement "memory" in computer.

the idea is that we have bunch of neurons, each one can be on or off. And each of them are connected to each other but one neuron is not connected to itself. and the connection is symmetric. 

Let's do an experiment with a specific example. Suppose we want to remember 5 x 5 pixel image like a T shape. then we will have 25-vector representing neurons' firing. the weight matrix will be 25 x 25, and its diagonal will be zero since no neuron connects to itself. The following is an image of a 8 neuron hopfield network


![hopfield network visualization](https://www.asimovinstitute.org/wp-content/uploads/2016/09/hn.png "hopfield network visualization")

In [ ]:
t_shape = [1,  1, 1,  1,  1, 
          -1, -1 ,1, -1, -1,
          -1, -1 ,1, -1, -1,
          -1, -1, 1, -1, -1,
          -1, -1, 1, -1, -1]

In [ ]:
c_shape = [1, 1, 1, 1, 1, 
           1,-1,-1,-1,-1,
           1,-1,-1,-1,-1,
           1,-1,-1,-1,-1,
           1, 1, 1, 1, 1]

The idea is that: can our network somehow remembers these two patterns and when given a input that is sorted of like T or sorted of like C, it would give back the original T or C shape? the answer is yes!

Now the learning phase is extremely simple, it is just the plain old Hebbian learning rule: **the neurons that fire together, wire together. The neurons that don't fire together inhibit each other**.

Mathematically the learning rule is:
$$W_{ij}(t+1) = W_{ij}(t) + \eta s_i s_j$$
where $W_{ij}$ is the connection strength from neuron j to neuron i. $\eta$ is the learning rate. $s_{i}, s_{j}$ are the firing pattern of neuron i, j.

Therefore if two neurons both are 1, or both are -1, their connection will strenght in the next time step, if two neurons are of opposite sign, their connection will weaken. And we will do this update rule across the entire network at the same time. in the matrix form we have:
$$W(t+1) = W(t) + \eta (ss^T - I)$$
where s is the neuron firing vector, and W is the weight matrix. We minus an identity matrix because if we don't do that $ss^T$ will add $1$'s on the diagonals, which we don't want.

In [ ]:
import numpy as np # linear algebra library in python

In [ ]:
# initializing weight matrix (5,5) of all zeros.
W = np.zeros((25,25))

In [ ]:
W

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [ ]:
# convert python list to numpy array for matrix multiplication
# calculations.
t_shape = np.asarray(t_shape)
c_shape = np.asarray(c_shape)

In [ ]:
# learning the T pattern in the weight matrix
W = W + 0.1 * (t_shape.reshape(25,1) @ t_shape.reshape(1,25) - np.eye(25))

In [ ]:
W

array([[ 0. ,  0.1,  0.1,  0.1,  0.1, -0.1, -0.1,  0.1, -0.1, -0.1, -0.1,
        -0.1,  0.1, -0.1, -0.1, -0.1, -0.1,  0.1, -0.1, -0.1, -0.1, -0.1,
         0.1, -0.1, -0.1],
       [ 0.1,  0. ,  0.1,  0.1,  0.1, -0.1, -0.1,  0.1, -0.1, -0.1, -0.1,
        -0.1,  0.1, -0.1, -0.1, -0.1, -0.1,  0.1, -0.1, -0.1, -0.1, -0.1,
         0.1, -0.1, -0.1],
       [ 0.1,  0.1,  0. ,  0.1,  0.1, -0.1, -0.1,  0.1, -0.1, -0.1, -0.1,
        -0.1,  0.1, -0.1, -0.1, -0.1, -0.1,  0.1, -0.1, -0.1, -0.1, -0.1,
         0.1, -0.1, -0.1],
       [ 0.1,  0.1,  0.1,  0. ,  0.1, -0.1, -0.1,  0.1, -0.1, -0.1, -0.1,
        -0.1,  0.1, -0.1, -0.1, -0.1, -0.1,  0.1, -0.1, -0.1, -0.1, -0.1,
         0.1, -0.1, -0.1],
       [ 0.1,  0.1,  0.1,  0.1,  0. , -0.1, -0.1,  0.1, -0.1, -0.1, -0.1,
        -0.1,  0.1, -0.1, -0.1, -0.1, -0.1,  0.1, -0.1, -0.1, -0.1, -0.1,
         0.1, -0.1, -0.1],
       [-0.1, -0.1, -0.1, -0.1, -0.1,  0. ,  0.1, -0.1,  0.1,  0.1,  0.1,
         0.1, -0.1,  0.1,  0.1,  0.1,  0.1, -0.1,  

In [ ]:
# learning the C pattern in the weight matrix
W = W + 0.1 * (c_shape.reshape(25,1) @ c_shape.reshape(1,25) - np.eye(25))

In [ ]:
# recall pattern from corrupted signal
corrupted_T = [ 1,  1, 1,  1,  1, 
               -1, -1 ,1, -1, -1,
               -1,  1,-1, -1, -1,
               -1,  1,-1, -1, -1,
               -1, -1, 1, -1, -1]

The "recalling mechanism" involves the neurons change each other's state based on its input until they settle down to a stable pattern:

randomly pick a neuron $s_i$, $s_i(t+1) = \sum_{j\ne i} W_{ij}s_j(t)$, do this long enough, hopefully we will have a stable network, and hopefully that is the pattern we want to remember.

In [ ]:
for i in range(100):
  new_vector = W @ corrupted_T
  corrupted_T = [1 if x > 0 else -1 for x in new_vector]

In [ ]:
corrupted_T = np.asarray(corrupted_T)

In [ ]:
corrupted_T.reshape((5,5))

array([[ 1,  1,  1,  1,  1],
       [-1, -1,  1, -1, -1],
       [-1, -1,  1, -1, -1],
       [-1, -1,  1, -1, -1],
       [-1, -1,  1, -1, -1]])

Yay! We recovered our T pattern!

In [ ]:
corrupted_C =[1, 1, 1, 1, 1, 
              1, 1,-1,-1,-1,
              1, 1,-1,-1,-1,
              1, 1,-1,-1,-1,
              1,-1,-1, 1, 1]

In [ ]:
for i in range(100):
  new_vector = W @ corrupted_C
  corrupted_C = [1 if x > 0 else -1 for x in new_vector]

In [ ]:
corrupted_C = np.asarray(corrupted_C)
corrupted_C.reshape((5,5))

array([[ 1,  1,  1,  1,  1],
       [ 1, -1, -1, -1, -1],
       [ 1, -1, -1, -1, -1],
       [ 1, -1, -1, -1, -1],
       [ 1,  1,  1,  1,  1]])

we recovered our C pattern as well!!! I think this is super cool, but obvious question remains: how many patterns can we remember? We certainly can't remember 1000 patterns with this mechanism? how much deviation from original pattern can we have but still retrieving the original pattern? (how much corrupted can data be?)

[play with hopfield network yourself on this website! the backend algorithm is exactly the same as in this notebook, but with cooler visualization](http://faculty.etsu.edu/knisleyj/neural/neuralnet3.htm)